'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Icon } from './Icons';
import { AiChatbot } from './AiChatbot';

type Listing = { id: string; title: string; location: string; price: string; intent: 'For rent' | 'For sale' | 'Book'; detail: string; rating: string; image: string; verified?: boolean };
type CategoryConfig = { name: string; eyebrow: string; description: string; cover: string; accent: string; filters: string[]; listings: Listing[] };

const listing = (id: string, title: string, location: string, price: string, intent: Listing['intent'], detail: string, image: string, rating = '4.8', verified = false): Listing => ({ id, title, location, price, intent, detail, image: title === 'Quiet home near Rebero' ? '/properties/house-01.jpg' : title === 'Development plot with city views' ? '/properties/land-01.jpg' : image, rating, verified });

const categoryConfigs: Record<string, CategoryConfig> = {
  houses: { name: 'Houses', eyebrow: 'Homes with room to live', description: 'Family homes, townhouses, and standalone properties across Kigali and beyond.', cover: '/properties/house-02.jpg', accent: '#39734b', filters: ['All homes', 'For rent', 'For sale'], listings: [listing('house-1', 'Four-bedroom home with garden', 'Gisozi · Kigali', 'RWF 1,250,000 / month', 'For rent', '4 beds · 3 baths · 220 m²', '/properties/house-01.jpg', '4.9', true), listing('house-2', 'Nyarutarama family residence', 'Nyarutarama · Kigali', 'RWF 2,400,000 / month', 'For rent', '5 beds · 4 baths · 310 m²', '/properties/house-02.jpg', '4.8', true), listing('house-3', 'Quiet home near Rebero', 'Rebero · Kigali', 'RWF 185,000,000', 'For sale', '4 beds · 3 baths · 280 m²', '/properties/kigali-neighborhood.jpg', '4.7')] },
  apartments: { name: 'Apartments', eyebrow: 'City living, made easy', description: 'Well-located apartments for renting, buying, and making Kigali your base.', cover: '/properties/apartment-01.jpg', accent: '#527b83', filters: ['All apartments', 'For rent', 'For sale'], listings: [listing('apt-1', 'Light-filled Kacyiru apartment', 'Kacyiru · Kigali', 'RWF 1,100,000 / month', 'For rent', '2 beds · 2 baths · 118 m²', '/properties/apartment-01.jpg', '4.9', true), listing('apt-2', 'Modern apartment near Kimihurura', 'Kimihurura · Kigali', 'RWF 1,650,000 / month', 'For rent', '3 beds · 2 baths · 145 m²', '/properties/apartment-02.jpg', '4.8', true), listing('apt-3', 'Compact city apartment', 'Kicukiro · Kigali', 'RWF 78,000,000', 'For sale', '2 beds · 2 baths · 94 m²', '/properties/apartment-02.jpg', '4.6')] },
  land: { name: 'Land', eyebrow: 'A better place to begin', description: 'Residential, commercial, and development plots with the location details to plan your next move.', cover: '/properties/land-01.jpg', accent: '#788f55', filters: ['All land', 'Residential', 'Commercial'], listings: [listing('land-1', 'Residential plot in Gacuriro', 'Gacuriro · Kigali', 'RWF 85,000,000', 'For sale', '620 m² · Residential · Road access', '/properties/land-01.jpg', '4.8', true), listing('land-2', 'Development plot with city views', 'Kicukiro · Kigali', 'RWF 120,000,000', 'For sale', '850 m² · Mixed use · Serviced', '/properties/kigali-neighborhood.jpg', '4.7'), listing('land-3', 'Growing neighbourhood plot', 'Gasabo · Kigali', 'RWF 48,000,000', 'For sale', '400 m² · Residential · Title ready', '/properties/land-01.jpg', '4.6')] },
  commercial: { name: 'Commercial', eyebrow: 'Spaces that mean business', description: 'Shops, workspaces, and commercial properties selected for visibility, access, and growth.', cover: '/properties/commercial-01.jpg', accent: '#9a6f4d', filters: ['All commercial', 'For rent', 'For sale'], listings: [listing('commercial-1', 'Street-facing commercial space', 'Remera · Kigali', 'RWF 1,900,000 / month', 'For rent', '180 m² · Retail · Parking', '/properties/commercial-01.jpg', '4.8', true), listing('commercial-2', 'Flexible office in Kicukiro', 'Kicukiro · Kigali', 'RWF 2,250,000 / month', 'For rent', '240 m² · Office · 2 baths', '/properties/commercial-02.jpg', '4.7', true), listing('commercial-3', 'Corner retail property', 'Nyabugogo · Kigali', 'RWF 265,000,000', 'For sale', '310 m² · Retail · Main road', '/properties/commercial-01.jpg', '4.6')] },
  offices: { name: 'Offices', eyebrow: 'A better place to work', description: 'Professional offices and flexible workspaces for teams building in Rwanda.', cover: '/properties/commercial-02.jpg', accent: '#527b83', filters: ['All offices', 'For rent'], listings: [listing('office-1', 'Flexible office in Kicukiro', 'Kicukiro · Kigali', 'RWF 2,250,000 / month', 'For rent', '240 m² · 2 baths · Parking', '/properties/commercial-02.jpg', '4.8', true), listing('office-2', 'Bright team workspace', 'Kacyiru · Kigali', 'RWF 1,450,000 / month', 'For rent', '120 m² · Furnished · Meeting room', '/properties/commercial-01.jpg', '4.7')] },
  equipment: { name: 'Equipment', eyebrow: 'Tools for the next project', description: 'Practical equipment listings from trusted local owners and businesses.', cover: '/properties/commercial-02.jpg', accent: '#65735f', filters: ['All equipment', 'For rent', 'For sale'], listings: [listing('equipment-1', 'Construction equipment package', 'Kigali · Rwanda', 'RWF 180,000 / day', 'For rent', 'Verified owner · Delivery available', '/properties/commercial-02.jpg', '4.8', true), listing('equipment-2', 'Commercial kitchen equipment', 'Remera · Kigali', 'RWF 7,500,000', 'For sale', 'Good condition · Inspection available', '/properties/commercial-01.jpg', '4.6')] },
  hospitality: { name: 'Hospitality', eyebrow: 'Stay somewhere memorable', description: 'Hotels, guesthouses, and short stays with clear booking details.', cover: '/properties/apartment-02.jpg', accent: '#9a6f4d', filters: ['All stays', 'Book now'], listings: [listing('hospitality-1', 'Kigali garden guesthouse', 'Kimihurura · Kigali', 'RWF 95,000 / night', 'Book', '2 guests · Breakfast · Wi-Fi', '/properties/apartment-02.jpg', '4.9', true), listing('hospitality-2', 'Quiet serviced apartment', 'Nyarutarama · Kigali', 'RWF 180,000 / night', 'Book', '4 guests · 2 beds · Kitchen', '/properties/apartment-01.jpg', '4.8', true)] },
};

export function CategoryExperience({ slug }: { slug: string }) {
  const category = categoryConfigs[slug] ?? categoryConfigs.houses;
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState(category.filters[0]);
  const [saved, setSaved] = useState<string[]>([]);
  const [activeListing, setActiveListing] = useState<Listing | null>(null);
  const listings = useMemo(() => category.listings.filter((item) => {
    const matchesQuery = `${item.title} ${item.location} ${item.detail}`.toLowerCase().includes(query.toLowerCase());
    const matchesFilter = filter.startsWith('All') || (filter === 'For rent' && item.intent === 'For rent') || (filter === 'For sale' && item.intent === 'For sale') || (filter === 'Book now' && item.intent === 'Book') || ['Residential', 'Commercial', 'Private office', 'Open workspace'].includes(filter);
    return matchesQuery && matchesFilter;
  }), [category, filter, query]);

  return <><main className="category-experience" style={{ '--category-accent': category.accent } as React.CSSProperties}>
    <header className="category-experience-header"><Link href="/" className="category-back"><Icon name="home" size={15} /> Home</Link><div><span>{category.name}</span><Link href="/">Umutungo <Icon name="arrow" size={14} /></Link></div></header>
    <section className="category-experience-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(8, 18, 10, .78), rgba(8, 18, 10, .2)), url(${category.cover})` }}><div><span className="category-experience-eyebrow">{category.eyebrow}</span><h1>Find your next<br /><em>{category.name.toLowerCase()} space.</em></h1><p>{category.description}</p></div><div className="category-search-box"><Icon name="search" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${category.name.toLowerCase()} by location or feature`} /><button type="button" aria-label="Search category" onClick={() => setQuery(query.trim())}><Icon name="arrow" size={15} /></button></div></section>
    <section className="category-experience-body"><div className="category-results-heading"><div><span className="category-experience-eyebrow">{listings.length} available now</span><h2>Explore {category.name.toLowerCase()}</h2></div><button className="category-map-button" type="button"><Icon name="pin" size={15} /> Map view</button></div><div className="category-filter-row">{category.filters.map((item) => <button className={filter === item ? 'active' : ''} key={item} type="button" onClick={() => setFilter(item)}>{item}</button>)}</div>{listings.length ? <div className="category-listing-grid">{listings.map((item) => <article className="category-listing-card" key={item.id} onClick={() => setActiveListing(item)}><div className="category-listing-image" style={{ backgroundImage: `linear-gradient(180deg, transparent 45%, rgba(5, 15, 8, .64)), url(${item.image})` }}><button className={`category-save ${saved.includes(item.id) ? 'saved' : ''}`} type="button" aria-label={`Save ${item.title}`} onClick={(event) => { event.stopPropagation(); setSaved((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id]); }}><Icon name="heart" size={16} filled={saved.includes(item.id)} /></button>{item.verified && <span className="category-verified"><Icon name="check" size={12} /> Verified</span>}</div><div className="category-listing-copy"><div className="category-listing-meta"><span className={`listing-intent ${item.intent === 'For sale' ? 'for-sale' : item.intent === 'For rent' ? 'for-rent' : ''}`}>{item.intent}</span><span className="category-stars">★ {item.rating}</span></div><h3>{item.title}</h3><p><Icon name="pin" size={13} /> {item.location}</p><div className="category-listing-footer"><div><strong>{item.price}</strong><small>{item.detail}</small></div><button className="category-view-button" type="button" onClick={(event) => { event.stopPropagation(); setActiveListing(item); }}>View property <Icon name="arrow" size={13} /></button></div></div></article>)}</div> : <div className="category-empty"><Icon name="search" size={21} /><h3>No listings match that search</h3><p>Try another neighbourhood, property type, or clear the filter.</p><button type="button" onClick={() => { setQuery(''); setFilter(category.filters[0]); }}>Clear search</button></div>}</section>
    {activeListing && <div className="category-detail-overlay"><button className="category-detail-backdrop" type="button" aria-label="Close property details" onClick={() => setActiveListing(null)} /><aside className="category-detail-panel"><button className="category-detail-close" type="button" onClick={() => setActiveListing(null)} aria-label="Close property details"><Icon name="x" size={17} /></button><div className="category-detail-image" style={{ backgroundImage: `url(${activeListing.image})` }} /><span className="category-experience-eyebrow">{activeListing.verified ? 'Verified listing' : 'Umutungo listing'}</span><h2>{activeListing.title}</h2><p className="category-detail-location"><Icon name="pin" size={14} /> {activeListing.location}</p><strong className="category-detail-price">{activeListing.price}</strong><p className="category-detail-description">{activeListing.detail}. This property has clear information and a local contact ready to answer your questions.</p><div className="category-detail-rating"><span>★★★★★</span><strong>{activeListing.rating}</strong><small>Verified reviews</small></div><button className="category-contact-button" type="button">Contact about this property <Icon name="arrow" size={15} /></button></aside></div>}
  </main><AiChatbot language="English" /></>;
}
